"""Compile one manifest into host-native files, without editing host settings."""

from __future__ import annotations

import hashlib
import json
from importlib.resources import files
from string import Template

from . import __version__
from .config import json_bytes, validate

COMMON_PATHS = {".orchatlas/.gitignore", ".orchatlas/lock.json", ".orchatlas/START.md",
                ".agents/skills/orchatlas/SKILL.md"}
HOST_PATHS = {
    "codex": {f".codex/agents/orchatlas_{role}.toml" for role in ("builder", "reviewer")},
    "opencode": {f".opencode/agents/{name}.md" for name in ("orchatlas", "orchatlas-builder", "orchatlas-reviewer")},
}
MANAGED_PATHS = COMMON_PATHS | HOST_PATHS["codex"] | HOST_PATHS["opencode"]


def digest(data: bytes | None) -> str | None:
    return hashlib.sha256(data).hexdigest() if data is not None else None


def template(name: str) -> str:
    return files("orchatlas").joinpath("templates", name + ".md").read_text(encoding="utf-8")


def workflow(config: dict, host: str) -> str:
    separator = "_" if host == "codex" else "-"
    builder = f"orchatlas{separator}builder"
    reviewer = f"orchatlas{separator}reviewer"
    review = "Review the actual patch against the baseline for specification compliance and code quality."
    if config["recipe"]["review"] == "independent":
        review = (f"Provide {reviewer} the baseline diff, task contract and worker evidence. "
                  "Have this separate reviewer inspect the result without editing. "
                  "The coordinator checks its findings and owns acceptance.")
    return Template(template("workflow")).substitute(
        builder=builder, review_step=review, max_fix_rounds=config["recipe"]["max_fix_rounds"])


def toml_agent(role: str, settings: dict) -> bytes:
    descriptions = {"builder": "Implement an OrchAtlas task bundle and return verification evidence.",
                    "reviewer": "Review an OrchAtlas patch without modifying the workspace."}
    data = {"name": f"orchatlas_{role}", "description": descriptions[role]}
    if settings["model"] != "inherit":
        data["model"] = settings["model"]
    if settings.get("effort"):
        data["model_reasoning_effort"] = settings["effort"]
    if role == "reviewer":
        data["sandbox_mode"] = "read-only"
    data["developer_instructions"] = template(role).strip()
    result = "# Generated by OrchAtlas. Update orchatlas.json, then preview/apply.\n"
    result += "\n".join(f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in data.items())
    return (result + "\n\n[agents]\nenabled = false\n").encode("utf-8")


def markdown_agent(role: str, settings: dict, instructions: str, independent: bool) -> bytes:
    permission: dict = {"task": "deny"}
    if role == "planner":
        task = {"*": "deny", "orchatlas-builder": "allow"}
        if independent:
            task["orchatlas-reviewer"] = "allow"
        permission = {"task": task}
    elif role == "reviewer":
        permission = {"*": "deny", "read": {"*": "allow", "*.env": "ask", "*.env.*": "ask", "*.env.example": "allow"},
                      "glob": "allow", "grep": "allow", "list": "allow"}
    frontmatter = {
        "description": {"planner": "Coordinate the installed OrchAtlas recipe.",
                        "builder": "Implement an OrchAtlas bundle and verify the result.",
                        "reviewer": "Read and review the patch supplied by the coordinator."}[role],
        "mode": "primary" if role == "planner" else "subagent",
        "permission": permission,
    }
    if settings["model"] != "inherit":
        frontmatter["model"] = settings["model"]
    if settings.get("effort"):
        frontmatter["reasoningEffort"] = settings["effort"]
    # JSON scalars/objects are valid YAML values, avoiding a YAML dependency.
    header = "\n".join(f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in frontmatter.items())
    return f"---\n{header}\n---\n\n{instructions.strip()}\n".encode("utf-8")


def launch_commands(config: dict) -> dict[str, str]:
    commands = {}
    if "codex" in config["hosts"]:
        planner = config["hosts"]["codex"]["planner"]
        command = "codex"
        if planner["model"] != "inherit":
            command += " --model " + planner["model"]
        if planner.get("effort"):
            command += " -c 'model_reasoning_effort=\"" + planner["effort"] + "\"'"
        commands["codex"] = command
    if "opencode" in config["hosts"]:
        commands["opencode"] = "opencode --agent orchatlas"
    return commands


def render(config: dict) -> dict[str, bytes]:
    warnings = validate(config)
    independent = config["recipe"]["review"] == "independent"
    outputs = {".orchatlas/.gitignore": b"local/\n"}
    skill = ("---\nname: orchatlas\ndescription: Coordinate substantial coding work with this project's "
             "OrchAtlas recipe and native Codex or OpenCode agents. Use for bounded implementation "
             "and review; keep trivial or explicitly single-agent tasks in the main thread.\n---\n\n"
             "# OrchAtlas\n\nThis project uses recipe `" + config["recipe"]["id"] + "@" +
             config["recipe"]["version"] + "`. Apply only the section for the current host.\n\n")
    for host, roles in config["hosts"].items():
        flow = workflow(config, host)
        skill += f"## {host}\n\n"
        skill += "Configured roles (model `inherit` retains the host's selection):\n\n"
        for role, settings in roles.items():
            if role == "reviewer" and not independent:
                continue
            effort = f", effort={settings['effort']}" if settings.get("effort") else ""
            skill += f"- {role}: `{settings['model']}`{effort}\n"
        skill += "\n"
        if host == "codex":
            skill += ("Use the selected root session as planner. If its model/effort differs from an explicit "
                      "planner setting above, report the mismatch and use the launch instructions in "
                      "`.orchatlas/START.md` for a new session. Agent files configure children only.\n\n")
            for role in ("builder", "reviewer"):
                if role == "builder" or independent:
                    outputs[f".codex/agents/orchatlas_{role}.toml"] = toml_agent(role, roles[role])
        else:
            skill += "Use the `orchatlas` primary agent (`opencode --agent orchatlas`).\n\n"
            outputs[".opencode/agents/orchatlas.md"] = markdown_agent("planner", roles["planner"], flow, independent)
            for role in ("builder", "reviewer"):
                if role == "builder" or independent:
                    outputs[f".opencode/agents/orchatlas-{role}.md"] = markdown_agent(role, roles[role], template(role), independent)
        skill += flow + "\n"
    outputs[".agents/skills/orchatlas/SKILL.md"] = skill.encode("utf-8")
    start = "# Start this OrchAtlas project\n\nRun these commands from the project root after applying the files.\n\n"
    for host, command in launch_commands(config).items():
        start += f"## {host}\n\n```sh\n{command}\n```\n\n"
        if host == "codex":
            start += "In the new session, request: `$orchatlas Implement <your task>.` Select/trust the project through the host's normal flow.\n\n"
        else:
            start += "The `orchatlas` primary agent contains the workflow. Describe your implementation task.\n\n"
    start += ("For an already open app, start a fresh session after configuration changes. "
              "Model/provider authentication remains with the host. Neither these files nor a successful "
              "configuration check proves that inference or delegation works.\n\n"
              "Generated files inherit existing host settings unless explicitly specified. "
              "Host overrides may take precedence, including sandbox permissions.\n\n")
    start += "## Configuration notes\n\n" + "\n".join("- " + warning for warning in warnings) + "\n"
    outputs[".orchatlas/START.md"] = start.encode("utf-8")
    lock = {"schema_version": 1, "compiler_version": __version__, "validation": "static-only",
            "runtime_verified": False, "manifest": config, "manifest_sha256": digest(json_bytes(config)),
            "files": {name: digest(content) for name, content in sorted(outputs.items())}}
    outputs[".orchatlas/lock.json"] = json_bytes(lock)
    return dict(sorted(outputs.items()))
